# Generated by Django 6.0.3 on 2026-03-20 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gehaltsmodell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('ARBEIT', 'Arbeitermodell'), ('FIX', 'Fixgehaltmodell')], default='ARBEIT', max_length=10)),
                ('stdlohn', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stdzahl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gehalt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mitarbeiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=30)),
                ('nachname', models.CharField(max_length=30)),
                ('gebdatum', models.DateField()),
                ('einstdatum', models.DateField()),
                ('geschlecht', models.CharField(choices=[('D', 'Divers'), ('W', 'Weiblich'), ('M', 'Männlich')], max_length=1)),
                ('gehaltmodell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.gehaltsmodell')),
            ],
        ),
    ]
